//Black cards (Questions)
var cards_blackCards = [
"After getting bored with the big flashlight, I stuck ______ up my ass" 
"Attractive, white, upper middle class males can't handle ______" 
"Because I've never experienced any form of hardship, I have no problem with ______" 
"I just got done serving a 10 year sentence for ______" 
"Instead of Viagra, I get my dick hard by ______" 
"The best part abot having a live in Grandparent with Dimentia is they will do just about anything. I have mine help me with ______"  
"Don’t open, ______ inside." 
"I can’t profess to understand God’s plan. Christ promised the resurrection of the dead. I just thought He had ______ in mind." 
"I’m looking for my family. They’re ______. Can you help me?" 
"Listen, damnit. You step outside, you risk your life. You take a drink of water, you risk your life. And nowadays you breathe, and you risk your life. Every moment now you don't have a choice. The only thing you can choose is what you're risking it for: ______." 
"Mother Fuckers. They're going to feel pretty stupid when they find out they're fucking with ______." 
"There's no way you can ever be ready for it. I try to be, but I can't. The best we can do now is avoid ______ as long as we can, keep one step ahead." 
"This is how we survive: we tell ourselves that we are ______." 
"What happens when the countdown reaches zero? ______" 
"When you care about people, ______ is kind of part of the package." 
"I once heard of a man who survived in a war zone simply by utilizing the power of ______." 
"In the absence of a gun, ______ can be excellent for self defense." 
"Never bring a ______ to a ______ fight.",2
"Players of PUBG have often requested a new game map based around the concept of ______." 
"Step one: deploy at the military base. Step two: acquire ______. Step three: win." 
"""You miss 100% of the ______ you don't ______. -Wayne Gretzky"" - Michael Scott" 
"""______ tomorrow, because today is almost over."" - Michael Scott" 
"Abraham Lincoln once said, ""If you are a racist I will attack you with ______."" - Michael Scott" 
"Angela’s cats are so cute you just want to ______ them." 
"Assistant to the regional ______." 
"Bears. Beets. ______." 
"Because of ______, I thought I might die, on beach day." 
"Break me off a piece of that ______." 
"If ______ ever wins an Oscar award, I am going to be a very rich dude." 
"Lord, beer me ______." 
"No its not ______, it’s Kevin Malone." 
"Question: What type of bear is best?" 
"When it comes to ______, everyone deserves a 2nd 2nd chance." 
"______ and ______. Taste like Splenda; gets you drunk like scotch." 
"______, HARDCORE PARKOUR" 
"______, it takes an advance sense of humor to understand" 
"______, you ignorant slut!" 
"______? Isn't that just a fancy word for ______?" 
"Halt! Any sudden moves and I put ______ right between your eyes!" 
"Here's how this thing's gonna play out. You don't bring up ______. Ever. Matter of fact, we can just keep ______ to ourselves. Secondly, don't tell anyone about ______. They’ll either think you’re crazy or they'll try to kill you. And lastly, you do what I say, when I say it. We clear?" 
"Honey, please not right now. I do not have the energy for ______." 
"If I ever were to lose ______, I’d surely lose myself." 
"One upon a time, I had somebody that I cared about. It was a partner. Somebody I had to look after. And in this world, that sort of shit is good for one thing: ______." 
"Really, Tommy? I bring you ______ and you wanna play the pissy little brother?" 
"The way I see it, we got two options. Option one: we take the easy way out. It’s quick and painless. I’m not a fan of option one. Option two: ______." 
"There’s a million ways we should’ve died before today. And a million ways we can die before tomorrow. But we fight... we fight for ______." 
"Why don't you say whatever speech you got rehearsed and get ______ over with." 
"You're right... you're not my daughter, and I sure as hell ain't ______." 
"After consultation with my Generals and military experts, please be advised that the United States Government will not accept or allow ______." 
"After years of railing against Obamacare, Paul Ryan finally had a chance to replace it with ______." 
"Are you really ______? Because that's hot." 
"At last, the ritual is almost complete. Only one thing remains: ______." 
"At this point, I have more evidence that ______ exists than I do for God." 
"How do you solve a problem like Maria?" 
"I got the results of the test back. I definitely have ______." 
"I never thought I'd die by ______, but I always hoped I would." 
"I've solved the mystery and I've gathered you all here to announce that one of you is ______." 
"It's important that all great works of art contain ______ so that it doesn't anger God." 
"Last night, I got the best sleep I've had in ages. The only thing I remember is dreaming about ______." 
"Look, this is all covered in my zeitgeist-defining self-published e-book: ""2017: The Year of ______.""" 
"Me: ______. Also me: ______." 
"My new favorite drink is called ""______."" It's better than it sounds." 
"NASA has announced the discovery of seven planets orbiting Trappist-1, all of which are potentially suitable for ______." 
"The Pope has recently updated the requirements for sainthood, which now requires two miracles or one miracle and ______." 
"This is fun and all, but it's not a real party until you're ______." 
"Why was I put on this Earth?" 
"What is your favorite penis?" 
"______ is best penis." 
"______ penis." 
"Chronic fatigue is usually a sign of ______." 
"I bought the remastered version of ______ for the extended cut of ______." 
"I couldn't sleep last night I was too distracted by ______." 
"I wasn't a fan of ______ until I experienced it for myself." 
"I'm suddenly having a massive craving for ______." 
"Life, liberty, and the pursuit of ______." 
"On this week's episode we will be having a serious discussion about ______, and how it affects ______." 
"Side effects may include ______ and ______." 
"______, because girls just wanna have fun." 
"______, the other white meat." 
"""Greetings, dear listeners. Won't you join ______ for ______?""" 
"90's Kid's favorite comic is ______." 
"A piece of ______ is missing." 
"A ______ Credit Card!?" 
"After getting snowed in at MAGfest, the reviewers were stuck with ______." 
"After ______, Phelous regenerated into ______." 
"ALL OF ______." 
"An intervention was staged for Linkara after ______ was discovered in his hat." 
"Arlo P. Arlo's newest weapon combines ______ and ______!" 
"As a way of apologizing for a poorly received episode, E Rod promised to review ______." 
"At ConBravo, ______ will be hosting a panel on ______." 
"At his next con appearance, Linkara will cosplay as ______." 
"At least he didn't fuck ______." 
"At MAGFest, ______ will host a panel focusing on ______." 
"Because poor literacy is ______." 
"Being done with My Little Pony, 8-Bit Mickey has moved onto ______." 
"Being fed up with reviewing lamps, what obscure topic did Linkara review next? ______" 
"Birdemic 3: ______" 
"Blip checks are way smaller in January so I'll spend the month riffing on ______ to gain more views." 
"Brad Tries ______." 
"Doug still regrets the day he decided to do a Let's Play video for ""Bart Simpson's ______ Adventure""." 
"E Rod has a new dance move called ______." 
"Enemies of Diamanda Hagan have been known to receive strange packages filled with ______." 
"Even Kyle thinks ______ is pretentious." 
"Florida's new crazy is about ______." 
"For a late night snack, Nash made a sandwich of ______ and ______." 
"For the next Anniversary event, the TGWTG producers must battle ______ to get ______." 
"Good evening! I am ______ of ______." 
"He is a glitch. He is missing. He is ______." 
"Hello, and welcome to Atop ______, where ______ burns." 
"Hello, I'm a ______." 
"Hello, I'm the Nostalgia Critic. I remember ______ so you don't have to!" 
"Here There Be ______." 
"Hey kids, I'm Nash, and I couldn't make ______ up if I tried." 
"Hey Nash, whatcha playin'? ______" 
"High and away on a wing and a prayer, who could it be? Believe it or not, it's just ______." 
"How is Bennett going to creep out Ask That Guy this time? ______" 
"I AM THE VOICELESS. THE NEVER SHOULD. I AM ______." 
"I asked Linkara to retweet ______, but instead, he retweeted ______." 
"I love ______. It's so bad." 
"I prefer for MY exploitation films to have ______, thank you very much." 
"I watch movies just to see if I can find a Big Lipped ______ Moment." 
"I write slash fanfiction pairing ______ with ______." 
"I ______ so you don't have to." 
"I'm going to die watching ______ review ______." 
"I'm looking forward to Jesuotaku's playthrough of Fire Emblem: ______." 
"If a dog and a dolphin can get along, why not ______ and ______?" 
"If I wanted to see ______, I'll stick with ______, thank you very much." 
"If you are able to deflect ______ with ______, we refer to it as ""Frying ______""." 
"If you value your life, never mention ______ around Oancitizen." 
"If ______ got to direct an Uncanny Valley short, it would have featured ______." 
"In a new latest announcement video, ______ has announced an appearance at ______." 
"In a surprise twist, the villain of Linkara's next story arc turned out to be ______." 
"In her newest review, Diamanda Hagan finds herself in the body of ______." 
"In his latest review, Phelous was killed by ______." 
"In his most recent Avatar vlog, Doug's favorite thing about the episode was ______." 
"In my new show, I review ______ while dressed like ______." 
"In the newest Cheap Damage, CR looks at the trading card game version of ______." 
"In trying to ban ______, Florida accidentally banned ______." 
"It was all going well until they found ______." 
"It's not nudity if there's ______." 
"IT'S NOT ______!" 
"JW confirms, you can play ______," 
"Kyle's next student film will focus on ______." 
"Last time I took bath salts, I ended up ______ in ______." 
"Leon Thomas almost named his show Renegade ______." 
"Linkara now prefers to say ______ in lieu of ""fuck""." 
"Linkara was shocked when he found out Insano was secretly ______." 
"Linkara's next story arc will involve him defeating ______ with the power of ______." 
"Linkara's Yu-Gi-Oh deck is built up with nothing but ______." 
"Luke Mochrie proved he was still part of the site by______." 
"Luke's newest character is ______, the Inner ______." 
"Make a WTFIWWY story. ______, ______, ______" 
"MikeJ's next sexual conquest is ______." 
"Nash had a long day at work, so tonight he'll stream ______." 
"Nash rejected yet another RDA request for ______." 
"Nash will build his next contraption with just ______, ______, and ______." 
"Nash's newest made-up curse word is ______-______-______!" 
"Nash's recent rant about Microsoft led to ______." 
"Nash's Reviewer Spotlight featured ______." 
"New rule in the RDA Drinking Game: Every time ______ happens, take a shot!" 
"Next January, the Nostalgia Critic is doing ______ Month." 
"Next time on Obscurus Lupa Presents: "" ______ IV: The Return of ______""." 
"No one wants to see your ______." 
"Of Course! Don't you know anything about ______?" 
"OH MY GOD THIS IS THE GREATEST ______ I'VE EVER SEEN IN MY LIFE!" 
"On the next WTFIWWY, Nash will give us a brief history of ______." 
"On the other side of the Plot Hole, the Nostalgia Critic found ______." 
"Putting ______ in ______? That doesn't go there!" 
"Reactions were mixed when ______ joined TGWTG." 
"Rock and Roll is nothing but ______ and the rage of ______!" 
"Sad Panda is actually ______ and ______." 
"Sage has presented JO with the new ecchi series ______." 
"Sean got his head stuck in ______." 
"Snowflame feels no ______." 
"Snowflame found a new love besides cocaine. What is it? ______" 
"So let's dig into ______ #1." 
"Some fangirls lay awake all night thinking of ______ and ______ together." 
"STOP OR I WILL ______." 
"Tara taught me that if you're going to engage in ______, then ______ isn't a good idea." 
"The best Bad Movie Beatdown sketch is where Film Brain ropes Lordhebe into ______." 
"The controversy over ad-blocking could be easily solved by ______." 
"The easiest way to counteract a DMCA takedown notice is with ______." 
"The invasion of Molassia was tragically thwarted by ______." 
"The last time Welshy and Film Brain were in a room together, they ended up ______." 
"The MAGFest Nerf War took a dark turn when ______ was waylaid by ______." 
"The new site that will overtake TGWTG is ______." 
"The newest fanfic trend is turning ______ into ______." 
"The newest Rap Libs makes extensive use of the phrase ""______.""" 
"The newest reviewer addition to the site specializes in ______." 
"The next crossover will have ______ and ______ review ______." 
"The next person to leave Channel Awesome will announce their departure via ______." 
"The next Renegade Cut is about ______ in a beloved children's movie." 
"The next TGWTG porn spoof? ______ with ______!" 
"The Nostalgia Critic will NEVER review ______." 
"The only thing Linkara would sell his soul for is ______." 
"The RDA chat knew Nash was trolling them when he played ______." 
"The real reason MAGFest was ruined was ______." 
"The reason Linkara doesn't like milk in his cereal is ______." 
"The secret of Linkara's magic gun is ______." 
"The theme of this week's WTFIWWY is ______." 
"The website was almost called ""thatguywith______.com""." 
"They even took ______! Who does that?!" 
"This week, Nash's beer is made with ______." 
"This weekend, the nation of Haganistan will once again commence its annual celebration of ______." 
"To top One More Day, future comic writers will use ______ to break up a relationship." 
"To troll the RDA chat this time, Todd requested a song by ______." 
"Todd in the Shadows broke the Not a Rhyme button when the singer tried to rhyme ______ with ______." 
"Todd knew he didn't have a chance after trying to seduce Lupa with ______." 
"Turns out, that wasn't tea in MikeJ's cup, it was ______." 
"Using alchemy, combine ______ and ______ to make ______!" 
"Viewers were shocked when Paw declared ______ the best song of the movie." 
"WAIT! I have an idea! It involves using ______!" 
"We all made a mistake when we ate ______ at MAGFest." 
"WE WERE FIGHTING LIKE ______." 
"Well, I've read enough fanfic about ______ and Lupa to last a lifetime." 
"Welshy is to ______ as Sad Panda is to ______." 
"What broke Nash this week? ______" 
"What delayed the next History of Power Rangers? ______" 
"What did Doug bring to the set of To Boldly Flee? ______" 
"What did the commenters bitch about next to Doug? ______" 
"What do Brad and Floyd like to do after a long day? ______" 
"What does Linkara eat with his chicken strips? ______" 
"What does Nash like to sing about? ______" 
"What does Todd look like under his mask? ______" 
"What does Ven have to do now? ______" 
"What doesn't go there? ______" 
"What doesn't work that way? ______" 
"What else does Diamanda Hagan have to live with every day? ______" 
"What hot, trendy new dance will feature in Paw's next Dance Spectacular? ______" 
"What is as low as the standards of the 90's Kid? ______" 
"What is hidden in Linkara's hat? ______" 
"What is in Sci Fi Guy's vest? ______" 
"What is literally the only thing tastier than a dragon's soul? ______" 
"What is Snowflame's only known weakness? ______" 
"What is the name of the next new Channel Awesome contributor? ______" 
"What is the real reason Demo Reel failed? ______" 
"What killed Harvey Finevoice's son? ______" 
"What made Dodger ban someone from the RDA chat this week? ______" 
"What new upgrade did Nash give Laura? ______" 
"What the fuck is wrong with you? ______" 
"What was the first sign that Linkara was turning evil? ______" 
"What will Nash try to kill next with his hammer? ______" 
"What will Tara name her next hippo? ______" 
"What's holding up the site redesign? ______" 
"What's really inside the Plot Hole? ______" 
"What's the real reason nobody has ever played the TGWTG Panel Drinking Game? ______" 
"What's up next on WTFIWWY? ______" 
"When Arlo The Orc turns into a werewolf, he likes to snack on ______." 
"When interviewing Linkara, be sure to ask him about ______!" 
"When is the next History of Power Rangers coming out? ______" 
"When not reviewing or ruling Haganistan with an iron fist, Hagan's hobby is ______." 
"When the JesuOtaku stream got to the ""awful part of the night,"" the GreatSG video featured ______." 
"Where'd he purchase that? ______" 
"Who REALLY called Oancitizen to help him snap out of his ennui? ______" 
"Whose ass did Zodann kick this time? ______" 
"Why can't Film Brain stop extending his final vowels? ______" 
"Why did Nash go to Chicago? ______" 
"Why does Linkara have all of those Cybermats? ______" 
"Why doesn't Doug ever attend MAGFest? ______" 
"Why doesn't Film Brain have an actual reviewer costume? ______" 
"Why was Radio Dead Air shut down this time? ______" 
"Write Linkara's next storyline as a haiku. ______, ______, ______" 
"You may be a robot, but I AM ______!" 
"______ and ______ are in the worst comic Linkara ever read." 
"______ and ______ would make awesome siblings." 
"______ did ______ to avoid ______." 
"______ didn't make it onto the first AT4W DVD." 
"______ is only on the site because of ______." 
"______ is part of the WTFIWWY wheelhouse." 
"______ is something else Diamanda Hagan has to live with every day." 
"______ is the reason Linkara doesn't like to swear." 
"______ is the reason that ______ picked ""AIDS.""" 
"______ is the subject of the Critic's newest review." 
"______ is the subject of the missing short from The Uncanny Valley." 
"______ is the theme of this year's anniversary crossover." 
"______ needs more gay." 
"______ should be on TGWTG." 
"______ was completely avoidable!" 
"______ was the first thing to go when Hagan took over the world." 
"______ will be Linkara's next cosplay." 
"______ will be the subject of the next TGWTG panel at MAGFest." 
"______ will live!" 
"______ wound up in this week's top WTFIWWY story." 
"______! What are you doing here?" 
"______! You know, for kids." 
"______. With onions." 
]



//White cards (Answers)
var cards_whiteCards = [
*liveshot*.
"8-Bit Mickey on an unstoppable merry-go-round."
"80's Dan."
"90's Kid's comic collection."
"90's Kid."
"A baseball to the nuts."
"A bat credit card."
"A Big Lipped Alligator Moment."
"A big long pink ding dong penis."
"A bird fucking a horse."
"A Blip ad for the most embarrassing reality show ever."
"A Blip check."
"A bootleg ninja turtle action figure possessed by Satan."
"A Brad Jones impersonation."
"A car landing on a roof."
"A case of disappearing bears."
"A Chia-Child."
"A congregation of bums."
"A crossover."
"A Crystal Pepsi&#194;&reg;-flavored enema."
"A Cybermat in a bow tie."
"A demonic Teddy Ruxpin doll."
"A disembodied orgasm hippo."
"A DMCA takedown notice."
"A doppelganger in black leather with a sword."
"A douchequake."
"A drugged Oancitizen in a schoolgirl outfit."
"A fan artist."
"A FUCKING PONCHO!"
"A giant go-fuck-yourself spider."
"A greased-up meth guy."
"A guest appearance by Giovanni Jones, the talking lobster."
"A half naked, fencing JewWario."
"A hand-basket of lobsters."
"A killer rabbit."
"A legion of mechawolves."
"A legion of spiders."
"A Linkara cameo."
"A mexican car wash."
"A misguided Tumblr activism campaign."
"A mobile meth lab in your pants."
"A Mr. T Trading Card."
"A naked rampage."
"A novelty slot machine."
"A Pan-Galactic Gargle Blaster."
"A pile of skulls."
"A pink tutu."
"A plushie cybermat."
"A plushie TARDIS."
"A poorly made knockoff action figure."
"A poorly-written ugly mess."
"A REALLY big hoopla about nothing."
"A really pimped out DeLorean."
"A secret goat porn stash."
"A Serbian Film."
"A smoking, muscled ice cream cone shooting guns and eye lasers."
"A speeding NERF dart to the junk."
"A squadron of attack Corgis."
"A squadron of line-dancing hippos."
"A strip-tease from the Nostalgia Critic."
"A talking snail in a suit."
"A tauntaun puppy."
"A tiny white dick."
"A titanic, undead, six-headed space dragon spewing bubbles."
"A very serious hat."
"A zombie fisherman."
"Accidentally punching your cohost in the face."
"ALL OF THE DICKS."
"ALL THE COCAINE!!!"
"Almost dying at Sesame Street."
"Ambiguously nude Linkara."
"An art film Kyle's reviewed."
"An autoclitorodectomy."
"An awkward slash fic between The Nostalgia Critic and The Angry Video Game Nerd."
"An electronic cigarette that resembles a Sonic Screwdriver."
"An elevator party."
"An evangelizing minion."
"An existential crisis over internet reviews."
"An impassioned plea for understanding."
"An obligatory cameo."
"An obscure reference only two people will get."
"An unhinged Oancitizen rolling towards the sea."
"Anal tearing."
"ANCIENT EGYPT!"
"Andrew Dickman."
"Angrily eating lettuce."
"Angrily playing piano."
"Angry Joe dancing in a squid suit."
"Angry Joe's raging boner."
"Angry Joe."
"Another fucking Iron Liz pun."
"Another goddamn PhilBuni Vine."
"Aplos, or Steve, the Wizard."
"Arlo P. Arlo."
"Arlo the Orc."
"Ash and Checkers."
"Ash."
"Ashens taking a blowtorch to a crappy toy."
"Ashens."
"Ask That Guy raped by Ma-Ti live."
"Ask That Guy With The Glasses."
"ASS ASS ASS ASS ASS ASS ASS ASS."
"Ass demons."
"Australia, Florida of the Pacific."
"Awkward pity sex with a sparkly teenage Cthulu."
"Bath salts."
"Because no one wants to see your dick."
"Because the Kool-Aid Man is red."
"Because there's nothing sexy at the Wal-Mart."
"Because...hippos."
"Becoming possessed and insulting your colleague."
"Bees!"
"Bees. My God."
"Being awkward around your favorite reviewer."
"Being frozen today."
"Bennett the Sage."
"Beppo the Invisible Monkey."
"BETRAYAL!"
"Big Butter Jesus."
"Big Jim Slade."
"Black Lantern Spoony."
"Blip."
"Blockbuster Buster busting a nut."
"Brad, drinking a Turkey-flavored Jones Soda."
"Breaking someone's spine by fucking."
"Bruno Matei."
"Butchered Dutch."
"Carl Copenhagen."
"Casper."
"ChaosD1."
"Chester A. Bum."
"Chuck Norris."
"Comicron One."
"Confusing The Last Angry Geek and Linkara."
"Corporate Commander."
"CR's collection of My Little Pony pins."
"CR."
"Creepy fans at cons buying expensive stuff for MarzGurl."
"Creepy guys in the RDA chat hitting on Tara."
"Crying your eyes out at a bunch of online reviewers."
"Crystal Pepsi&#194;&reg;."
"Cynthia Rothrock"
"Dark Nella."
"David Bowie's package."
"DEATH FROM ABOOOOOVE!!!"
"Derek the Bard's hat."
"Derek the Bard."
"Diamanda Hagan's sexbot."
"Diamanda Hagan."
"Diamanda's copy of Cockhammer."
"Disney's Anne Frank."
"Disturbing comments in the RDA chat."
"Dodger of Zion."
"Dodger's ban chain."
"Dodging blowjobs."
"Dogs wearing pantyhose."
"Dolphin rape."
"Dominic the Bartender."
"Dr. Insano."
"Dr. Tease & Dr. Block."
"Dr. Wiki."
"Dragging Oancitizen back home from a wild night of partying."
"Dump cards."
"E Rod's smooth, smooth dance skills."
"Eating the flesh of your foes while howling at the moon."
"Enoby Dark'ness Dementia Raven TARA Way."
"Evilina's monstrous visage."
"Evilina."
"Explosively masturbating with Malachite's Hand."
"Ferdinand Von Turrell."
"Film Brain's hair."
"Film Brain's lovely accent."
"Film Brain, dressed tastefully in fashionable clothing."
"Film Renegado creaming himself over Pacific Rim."
"Filmbrain."
"Finding out that ""it's not Pop Tarts!"""
"Firing a blue shell at the opposing house ship."
"Florida Man."
"Florida."
"Flying sex snakes in monocles and bow ties."
"Forcing an NPC to haul your crap."
"Fort Super-Awesome."
"FOUR HOURS?!"
"Frying the Coke."
"Fuck yeah, SPARKLE SPARKLE SPARKLE!"
"Fuck you, I do what I want."
"FUCK YOU, I'M SPIDERMAN!"
"Fucking bubbles."
"Fuckstick the Magic Dragon."
"Gargoyle Cat."
"Getting buggered by a giant hamster."
"Getting mauled by a mountain lion AND a grizzly bear at the same time."
"Glenn Beck being torn apart by zombies."
"Going full retard."
"Going through the effort to build a wall in your back yard just to bash your head into it over and over again."
"Gooby."
"Hagan's dictator tendencies."
"Hagan's make up artist."
"Hagan's masturbating minion."
"Haganistan."
"Ham?"
"Harmony Korine."
"Harvey Finevoice's fine voice."
"Having sex at a screening of Mr. Popper's Penguins."
"Hippo Queen Tara."
"HIPPOS!"
"Hitler without the mustache."
"Holly."
"Humping a can of trash."
"I AM A MAN!"
"Il Neige in a freakishly accurate Film Brain costume."
"Invading a micronation in Nevada and making it your own."
"Iron Liz."
"Jaeris, the Gunslinger."
"JewWario's solar penis."
"JewWario."
"Joe Quesada."
"Kali."
"Kickassia."
"Killing clowns."
"Kitler."
"Kung Tai Ted."
"Kyle humping a trashcan."
"Kyle playing GTA while drunk."
"Kyle's ""unicorns."""
"Laura, the Fender Stratocaster Goddess."
"Linkara crying in his Gatorade made of cybermat tears."
"Linkara lying naked on his futon, playing with a Cybermat."
"Linkara stalking Gail Simone on Twitter."
"Linkara's 'special' comic books."
"Linkara's cybermat invasion force."
"Linkara's fangirl support group."
"Linkara's futon."
"Linkara's hat."
"Linkara's magic gun."
"Linkara's masculine arms."
"Linkara's massive ego."
"Linkara, dressed as the Green Ranger."
"Linkara, dropping an F-Bomb."
"Linkara, sexily eating a salad."
"Linkara."
"Literally drinking bottled fangirl tears."
"Little Pluckies Ninja Protects."
"Lord Vyce."
"LordKaT's used nipple tassles."
"Luke Mochrie's trust fund."
"Luke's curly hair."
"Luke's inners."
"Luke."
"Lupa's brand of hair dye."
"Ma-Ti being castrated and having his balls shipped to Oancitizen in the mail by Diamanda Hagan."
"MAGfest."
"Magical fairy sex."
"Making angry love to a DVD copy of ""Neverending Story III""."
"Mako."
"Malachite's Hand."
"Malachite."
"Mary Sewage."
"Marzgurl."
"Marzkara fanfiction."
"Maven of ze Eventide."
"Maven's secret sparkling vampire dildo."
"Mechakara's phallic drill."
"Mechakara."
"Melvin, brother of the Joker."
"Mexican Spider-Man."
"MikeJ."
"Moarte."
"My mom."
"My penis catching fire."
"Naked crazy."
"Nash breaking his ass."
"Nash dressed in drag."
"Nash in a gimp suit."
"Nash popping a blood vessel over Florida."
"Nash's creepy face."
"Nash's folksy, velvety voice."
"Nash's long, long hair."
"Nash, dressed as The Undertaker."
"Nash, making ""vroom vroom"" noises."
"Nash, making train sounds in a bathtub."
"Nash."
"Nella's cleavage Altoids."
"Nella."
"Newborn porn."
"Not reading the FAQ."
"Nun fuckery."
"Oancitizen."
"Obelisk Blue Linkara."
"Obscurus Lupa."
"Only being on the site because of the influence of famous acquaintences."
"Over-intrusive fanboys."
"Pants that need to be darkened."
"Paw's soul patch."
"Paw."
"Penis whiskers."
"Phelous making love to his Turtles collection."
"Phelous."
"PhelousD1."
"PhilBuni."
"Playing TGWTG Cards Against Humanity at stupid o'clock."
"Pol Pot pies."
"Poop, as a plan."
"Punching your foe in the stomach and screaming ""I AM A MAN!"""
"PushingUpRoses' bird tattoos."
"Putting sexy pantyhose on your dog."
"Rachel Tietz, trying to Kill the Nostalgia Critic."
"Radio Dead Air."
"Rapidly pounding themselves in the face with a hammer."
"Reading fan fiction on a live stream."
"Requesting John Cage's ""4'33"" on Radio Dead Air."
"Reviewer dibs."
"Reviews of $20 lamps."
"Ripping off part of your penis."
"Rob Liefeld."
"Robotic sex slaves that are made to feel sadness."
"ROCKET BOOTS!"
"ROCKET PUNCH!"
"Rule 34 of Linkara and a lamp."
"Sad Panda's lanky, manly chest."
"Sad Panda."
"Sage's ""RAPE!"" face."
"Santa Christ's raging boner."
"Santa Christ."
"Sci-Fi Guy's ponytail."
"Sean."
"Sex, violence, and Daffy Duck screaming."
"Sharkleberry Finn-flavored Kool-Aid."
"Shooting colored corn syrup up your nose."
"Shouting ""FUS-RO-DAH!"" at a puppy."
"Skitch."
"Slightly creepy comments about Tara's hair."
"Smarty's special bag of AIDS."
"Smarty."
"Smoking kittens."
"Snowdicking."
"Snowflame's cocaine flavored popsicles."
"Snowflame's fuzzy slippers."
"Snowflame, feeling no pain."
"Sodomizing a loved one with a baseball bat."
"Space Core."
"Space Guy."
"Spoony's fans."
"Stealing money off dead wolves."
"Stick figure porn."
"Stickboy."
"Storing your dead friend's ashes into a Quaker Oats can."
"Suggestively eating a banana at the sight of David Bowie."
"Superboy Prime."
"Surprise blowjobs."
"SYMBOLISM!"
"Taking someone by the shoulders, throwing them on the bed and riding them like a stallion."
"Tara's tramautic childhood stories."
"That Aussie Guy."
"That Dude In The Suede."
"That goddamned Colossus roar."
"That one guy with snails."
"That Sci-Fi Guy."
"The Adventures of Horsemeat and the Placenta #1."
"The Amazing Bulk."
"The Angry Video Game Nerd."
"The Blockbuster Buster."
"The Channel Awesome satellite."
"The Cinema Snob Movie DVD."
"THE COCK."
"The Continuity Alarm."
"The elephant in the room."
"The Entity."
"The Executor."
"The Film Renegado."
"The five months when the Nostalgia Critic was dead."
"The Gooby Curse."
"The Hippo Lantern Corps."
"The LAAAAAAAAAAAAAAAAAAAAAW!"
"The Last Angry Geek."
"The legendary MAGFest orgy."
"The Longbox of the Damned."
"The Makeover Fairy."
"The most important job, reviewing a crappy comic book."
"The next History of Power Rangers."
"The Nostalgia Critic."
"The Nostalgia Ranger."
"The pig fucking movie."
"The plot hole."
"The Power Glove."
"The Rap Critic."
"The RDA drinking game."
"The RDA IRC channel."
"The Spocker."
"The TGWTG site redesign."
"The thick, muscular arms of ChaosD1."
"The Trousers Cosmic."
"The Uncanny Valley."
"The Wal-Mart."
"The Wunder Boner."
"This fecal matter you call ""Fluttershy""."
"Throwing a Baby Tumbles Surprise down a staircase."
"Time travel."
"Timing."
"Todd in the Shadows."
"Todd trolling Chris Brown on Twitter."
"Todd's unmasked visage."
"Tommy Wiseau."
"Turtle."
"Twin clones of Hitler."
"Using a frontloader to steal deodorant."
"Using Crystal Pepsi as a substitute for lube."
"Using donation money for weed."
"Using your underwear to shoplift raw meat from your local Wal-Mart."
"Vangelus"
"Ven Gethenian."
"Ven's voice, a gift from the fairies."
"Vigorously shagging your sister while holding a mug of warm tea."
"Welshy."
"Whatever the hell Barfiesta was supposed to be."
"Y Ruler Of Time."
"Yet another Thunderdome reference."
"Youngblood's disease."
"Zeo Linkara."
"Zodan The Unbouncable."
"Zodd."
"60 fps."
"A comedic roast gone too far."
"A craving that only hands could satisfy."
"A dance with the devil in the pale moonlight."
"A fake American accent."
"A gargantuan bag of dicks."
"A legitimate psychological condition."
"A low carb diet relapse involving Krispy Kreme&reg; doughnuts."
"A monologue of Quentin Tarantino caliber."
"A rigamortis induced boner that no woman could resist."
"A sippy cup filled with spicy dick milk."
"A surgically accurate gaydar."
"A transgender prostitute."
"A youtube black hole."
"Actual cannibal, Shia LaBeouf."
"Adam West Batman VS Christian Bale Batman."
"Affirmative action."
"All natural, locally grown, organic bullshit."
"An Assgasm."
"An epic fail."
"An inside joke, like way inside."
"Aspiring Youtubers."
"Bassists".
"Batfleck."
"Binge watching shows on Netflix&reg;."
"Blood orgies!"
"Completely cracking under the pressure."
"Death by horse fucking."
"Drummers."
"Dumpster diving for furniture."
"Easy money."
"Existential disagreements."
"Exploding kittens."
"Facebook stalking."
"Falling in love for the first time."
"Food carts."
"George R.R. Martin’s Livejournal."
"Ghost Peppers."
"Guitarists."
"Hitting a little too close to home."
"Intellectual Property."
"Internet culture."
"Kombucha."
"Lying about something to seem cool."
"Making it Steampunk."
"Manic depression."
"My inevitable death."
"My under utilized skills."
"Nickelback."
"Nihilism."
"Obscure 70’s rock bands only your father would know."
"Our dark lord and savior, Satan."
"Owning every season of Family Matters."
"Owning every season of Full House."
"People who actually think Taco Bell&reg; is Mexican food."
"Playing The Sims&reg; all night."
"Porn addiction."
"Prophetic visions induced by psychedelic drugs."
"Quitting while you’re ahead."
"Really really bad karaoke."
"Recording your neighbors daily lives."
"Registered sex offenders."
"Resting bitch face."
"Roast beef pussy."
"Robin Williams suicide note."
"Spontaneous orgasms."
"Taking credit for someone else’s work."
"That friend who's always talking about killing themselves, and it secretly makes you wish they would."
"That small window of time when food is expired but still edible."
"The anti vaccine movement."
"The Blu Ray edition."
"The controversial views expressed in the commentary."
"The inevitable icy death of the universe."
"The keyboard player."
"The man juice diet."
"The Marvel Cinematic Universe."
"The pure satisfaction of a perfectly timed &ldquo;That’s what she said&rdquo; joke."
"The rape of your childhood."
"The shit Mormons claim to believe."
"The Super Mario Brothers movie."
"The surprisingly good soundtracks of the Twilight movies."
"This shit is bananas, B A N A N A S!"
"TLC reality shows."
"Torture porn."
"Total isolation."
"Trollface."
"Urban Hippies."
"What I’d like to do to you."
"YOLO BITCHES!"
"Your old Myspace profile."
"A bondage slave in a diaper being spanked by a wire coat hanger saying ""ohh, yeah, abort me Daddy!"""
"A cancer stricken child's final fart"
"A German candle"
"A holocaust blooper reel"
"A joke too funny for women to understand"
"A sad old man buying cat food because his wife used to do all the cooking"
"A straight, white, able-bodied, incredibly attractive male from an upper-middle class family who has never undergone a single hardship."
"All the Neopets you left forever starving but never dying"
"an all you can scrape Abortion buffet!"
"Baby bottles with cock shaped nipples"
"Being unimpressed by a mass shooting's body count"
"Blowing a load of hot cum onto the face of a crying infant"
"Cable ties and chloroform"
"Caitlyn Jenner's rock-hard cock"
"Crotchless toddler underwear"
"Crying yourself to sleep as Uncle Jack makes love to your mother"
"Dressing up as your dad and raping your mom"
"Eating your granmas dusty old pussy"
"Father's day in the ghetto"
"gang rape/murder by a herd of HIV positive Elephants"
"gang rape/murder by a herd of HIV positive gorillas"
"Getting a job at a morgue for the free sex"
"Getting a prostate exam from a leper who walks away with four fingers"
"Giving birth to and raising my rapist's son"
"Half an 8-year-old finishing the Boston Marathon"
"Hate-fucking the girl who broke your heart while she is in a coma"
"Having your intestines sucked out by a pool drain"
"Hiding AIDS needles in the ball pit at Chuck-E-Cheese"
"hitler youth easy-bake ovens"
"Hitler's Barbe-Jew Sauce."
"Hitler's House of BBQ"
"Jacking off onto your ex's wedding cake and telling everyone it's just frosting"
"Luring an unsuspecting toddler into my bouncy castle of seduction."
"Murdering homeless people"
"not making it through the Batman premiere"
"orange jews, from 100% concentrate"
"Rubbing Robin Williams' urn to get 3 wishes"
"Sex with vegetables (either kind)"
"Stigmata handjobs"
"Sucking on an anal prolapse"
"Superman's other weakness: Horseback Riding"
"Taking it too far"
"The Burning Bush: A heal by prayer STD clinic"
"The Guilty Orgasm of a Rape Victim."
"The resurrected Jesus Christ, using the holes in his hands to masturbate"
"The soft silky interior of an unwilling sheep"
"The statistically 9 out of 10 people who enjoy gang rape."
"The terrifying sex moans of a deaf woman"
"Wiping cum and clown makeup off with the diaper"
"Wringing out a used fleshlight into your roommates morning protein shake"
"A barn that's perfect for storing human bodies."
"A big macho man who uses his muscles for good."
"A big, dangerous guy who wants to kill us."
"A black character whose catchphrase is ""Aw hell naw""."
"A bond of friendship greater than any force in the universe."
"A bottomless well of horrors."
"A catholic priest that actually respects boundaries."
"A charred corpse clawing its way out of the flames."
"A child beckoning me into the woods."
"A conveniently-timed thunder clap."
"A corpse with hope in its eyes."
"A crossbow bolt straight to the heart."
"A dead guy."
"A decomposing toddler."
"A diverse cast of likable characters."
"A fascinating mullet."
"A figment of the imagination."
"A fucking hatchet."
"A full pantry, a warm bed, and advanced plumbing."
"A good dog."
"A graveyard smash."
"A guy named Rick."
"A horsey!"
"A human corpse dangling from a meat hook."
"A motherfucking crossbow."
"A person full of blood."
"A secret tribe of seafaring lady warriors."
"A simpler time when men were men and women were sex slaves who did laundry."
"A slowly expanding puddle of blood."
"A stab wound, an explosion, and a fall from a great height."
"A tank. A motherfucking tank. Can you believe that?"
"A total misinterpretation of the source material."
"A very dead baby."
"A whole entire barn."
"Abandoning a racist on a rooftop."
"Aimlessly floating downriver."
"All out war."
"All the flesh melting off of my body."
"All these dead bodies."
"An 80% mortality rate."
"An emotional gravity that can only be created by a good book or the death of your firstborn."
"An entire church congregation’s collective screams."
"An incestuous manipulative necro-pedophile rapist with a Fu Manchu who chops people’s heads off for fun."
"An unfortunate misinterpretation of the Bible."
"An unnecessary amount of tigers."
"Another show about a bland frowning white man with stubble."
"Begging God for the sweet release of death."
"Being a goddamn badass."
"Being all stinky."
"Being impaled and escaping from death by the sheer power of my own will to live."
"Being missing and presumed dead."
"Being so sad all the time."
"Being tricked, backstabbed, and quite possibly bamboozled."
"Biochemical warfare."
"Bleeding and crying and stuff."
"Bleeding everywhere."
"Blood and guts all over me."
"Botching an execution."
"Burning a man's eyelids off with a hot iron."
"Burning half my face off with a waffle iron."
"Burning people alive."
"Bustin' into tears."
"Changing my pronouns to ""your majesty&rdquo;."
"Chaos and bloodshed."
"Childhood innocence."
"Chronic masturbation!"
"Cicadas up the wazoo."
"Closing my eyes for the last time."
"Collapsing in grief."
"Coming into someone’s life, making them care, and then just checking out."
"Confessing my sins."
"Crushing the skulls of enemies underfoot like autumn leaves."
"Crying about the dead baby."
"Crying in the shower."
"Crying into a bottle of peach schnapps."
"Cutting down children with a katana."
"Cutting off a boy’s tongue as a power move."
"Dangling from a noose."
"Death on a scale that can only be described as ""biblical""."
"Debilitating childhood trauma."
"Decapitating a farmer."
"Decaying away into nothingness."
"Demanding that everyone lower their weapons right now so we can talk this out."
"Dismemberment."
"Drifting in and out of consciousness."
"Dubious pseudoscientific nonsense."
"Dying in my bed surrounded by my friends and family."
"Dying right now in a fiery explosion due to the carelessness of a friend."
"Eating many little girls."
"Endless fields of corpses."
"Fairly violent seizures."
"Falling down an elevator shaft."
"Falling into a deathlike slumber for several months."
"Falling into a ravine."
"Fear mongering."
"Finding the strength to go on."
"Gargling blood as I lie dying on the floor."
"Getting bonked on the head and becoming unconscious."
"Getting caught in a bear trap."
"Getting clubbed."
"Getting everybody killed."
"God, guns, grits, and gravy."
"Going cannibal."
"Going fucking berserk."
"Going out in a blaze of glory."
"Grunting in dismissal."
"Grunting repeatedly, like a man."
"Hearing for the first time that my child bit someone."
"Hiring the guy who made Ghost Rider 2: Spirit of Vengeance and just expecting everything to turn out okay."
"Holding me tight and telling me everything will be okay."
"How revolutionary trains were."
"Infant chunks."
"Just surviving somehow."
"Killing all the men."
"Killing someone and wearing their face."
"Killing without remorse."
"Latching onto a man's throat and biting out his pulsing jugular."
"Long, solemn silences."
"Losing my favorite arm."
"Losing my grip on reality."
"Losing the will to live."
"Lying down in the dirt and letting the earth slowly reclaim me."
"Making an example of this kindly old man here."
"Mass graves."
"Masturbating to my dead spouse’s final voicemail message."
"Me and the other wolf boys."
"Meat from a can."
"Murmuring to myself that this isn't real, that this isn't happening, that I need to wake up."
"My daddy, the congressman."
"My first shower in months."
"My slowly draining sanity."
"My trusty hacksaw."
"Napalm."
"Nearly forming a coherent sentence."
"Needless cruelty."
"Norman Reedus’ son, Mingus Reedus."
"Ominous whistling."
"Our capitalist overlords."
"Our most basic primal instincts."
"Our random and cruel universe."
"Partial decapitation."
"Physical abuse."
"Punishment."
"Quietly sobbing around a mouthful of dick."
"Rapidly deteriorating peace talks."
"Raping, pillaging, and plundering."
"Realizing that I’m the asshole."
"Refugees that aren't so bad after all."
"Repopulating the earth."
"Rinsing off all the blood."
"Ripping an elderly boy open."
"Ripping open a pregnant woman and tearing out the screaming blood-soaked fetus."
"Rolling around in the grass because I am a severed head."
"Roundhouse kicking a man in the face."
"Scooting under a dumpster."
"Sensitive cowboys just looking for love."
"Several knives."
"Shit that happens."
"Shock value."
"Shooting a propane tank and it's exploding and now we’re all on fire."
"Shooting on sight."
"Shooting people with guns like a big boy."
"Shuffling off this mortal coil."
"Signing up for AMC Premiere and then regretting signing up for AMC Premiere."
"Sitting in the corner and thinking about what you've done."
"Skin. Just the skin."
"Slamming into a table and perishing."
"Slowly bleeding out."
"Slowly rotating on a stick over a roaring fire."
"Slowly wringing the life out of this fella."
"Smashing into a window at full speed."
"Society."
"Southern values."
"Spending quality time at home with what remains of my family."
"Spluttering and convulsing."
"Spreading Socialism to all who will listen."
"Stabbing me with knives."
"Still being alive, I guess."
"Stuff and things."
"Suddenly being forty years old."
"Suffering."
"Taking a head as a trophy."
"Tearfully putting down my best bro."
"The baby inside me."
"The benefits of suicide."
"The blood. Oh God, the blood."
"The choke hold."
"The easy way out."
"The eerie squelch that emanates from a grown man’s head when you crush his temple with a crowbar."
"The end of civilization."
"The end of the fucking world."
"The gallows."
"The guilt that pervades my very being."
"The gun I keep on my person at all times."
"The inherent trust I place in my father."
"The lone desperado riding into town."
"The moral ambiguity of my violent actions."
"The most powerful thing of all: friendship."
"The piked skull of the last person who dared cross into our land."
"The pleasure I experience from dissecting my sibling."
"The rash and emotionally driven impulses of a thirteen-year-old boy."
"The reality that we're all going to die, and there will be no one to remember our stories."
"The smell of rotting meat."
"The sound of breaking bones."
"The visceral pleasure of revenge."
"This curious and highly inventive structure called a windmill."
"This red machete that I promised to kill you with."
"Unnecessary profanity."
"Visiting my son in prison."
"Waking up in an abandoned hospital."
"Wearing a trench coat to let everyone know you’re hip and mysterious."
"Wearing an eyepatch and being a bad guy."
"Wearing skin suits to infiltrate their ranks."
"Wearing the ears of the men I’ve killed."
"Wrapping barbed wire around a baseball bat to memorialize my cancer-stricken wife and beating an Asian boy to death with it."
 "A 14 year old boy calling a grown white man the ""n word""."
"A bush that looks like a man."
"A crossbow bolt straight to the heart."
"A duel to the death."
"A slowly encroaching circle of lightning."
"A Volkswagen van that doubles as a Mexican stereotype."
"A whole bucket of chicken."
"An 8x8 kilometer island used for hunting other humans."
"An energy drink so delicious that it brings you back from the brink of death."
"Another YouTube Let's Play."
"Beating a man to death with my bare hands."
"Downing an entire bottle of pain killers."
"Getting dropped out of an airplane against your will."
"Getting naked and jumping."
"Getting run over by a dune buggy."
"Getting shot and not even being mad because it was pretty impressive."
"How it feels to be on the receiving end of an air strike."
"Ironically getting shot in a hospital."
"Kleptomania."
"Lag."
"Running over my best bro."
"Russian architecture."
"Shitty female voice actors."
"Sick motorcycle stunts."
"Skydiving accidents."
"Stalking my prey."
"Talking to strangers."
"That goddamn television playing in the background."
"That one guy that went off on his own and never came back."
"The hunger games, but with even more 12 year olds."
"The pan!"
"The right time to strike."
"The soothing touch of my best friend to make me feel all better."
"The subtle difference between cries of pain and cries of ecstasy."
"The tiny bit of sanity I lose every time I purchase another beanie hat."
"A well-timed ""that's what she said."""
"A well-timed &ldquo;thats what she said&rdquo;"
"Afghanistananians"
"Anal fissures"
"Beets."
"Being the fucking lizard King"
"Being unable to escape a conversation with Kelly Kapoor"
"Blind Guy Mc Squeezy"
"Count Choculitis."
"Crushing an apple with my hands to threaten people"
"Crushing your wife during sex"
"DECLARING BANKRUPTCY."
"Dinkin flicka."
"Dr. Crentist, D.D.S."
"Football cream."
"Going mach 5."
"Hitting on an engaged woman"
"Hooking up with your co-worker on February 13th"
"Hot Dog Fingers."
"Hotel Hell. Check-in time is now,check-out time is never."
"It’s Brittany Bitch"
"Jan Levinson-Gould's thousand-yard stare."
"Jimothy."
"Just a little Zing and Pep"
"Justice Beaver."
"Kleenex shoes"
"Me and the blues"
"Mmmmmmilf"
"Mr. Buttlicker"
"Mr. Poopy-Butthole"
"Not having enough orange traffic cones"
"Not superstitious, but a little stitious."
"Pippity poppitygimme the zoppity."
"Pretzel Day."
"Slow moving, inatentive, dull, constantly snacking, shows a lack of motivation"
"Soup snakes."
"Spreading Kevin’s Famous Chili all over myself"
"That face John Krasinksi makes."
"The Sabre Pyramidtablet."
"Two-way petting zoo."
"Waking up to the smell of bacon in the morning."
"&hellip; Pausing for dramatic effect."
"A 12-gauge slug to the balls."
"A basement full of weed."
"A big hot fire that's burning everybody."
"A big sewer full of so many skeletons."
"A big, dangerous guy who wants to kill us."
"A bigger, badder wolf."
"A bit of fungus around the bumhole."
"A bit of harmless brain alteration."
"A bond of friendship greater than any force in the universe."
"A brave, beautiful man who I am reliant on."
"A bunch of guys eating another guy."
"A charred corpse clawing its way out of the flames."
"A cheerfulness that belies a deep-seated self-loathing."
"A Chelsea smile."
"A child-sized grave."
"A childless marriage."
"A chiseled jawline and piercing brown eyes."
"A complete inability to understand anyone else's perspective."
"A complicated relationship with my father figure."
"A constant need for validation."
"A crossbow bolt straight to the heart."
"A dead guy."
"A deeply satisfying emotional experience."
"A deserted factory somewhere in rural Colorado."
"A dinosaur in a cowboy hat."
"A diverse cast of likable characters."
"A dozen ravenous wild monkeys."
"A drug-induced coma."
"A duel to the death."
"A faded polaroid of Leah’s right tit."
"A father's devotion."
"A ferny grotto."
"A fist-wide gunshot wound from a .44 magnum."
"A fit of rage."
"A five-minute dance break."
"A freezer full of mystery meat."
"A fucking hatchet."
"A fully-dressed female video game character."
"A fungal beast that, when destroyed, explodes into more, tinier fungal beasts."
"A funkadelic bass rift."
"A gay."
"A genderless hole."
"A giraffe, I think."
"A gnawing sense of dread."
"A good dog."
"A gun."
"A hail of bullets."
"A hatchet lobotomy."
"A hellish cacophony of moaning."
"A hellish gauntlet of murder gangs who kill for sport."
"A homoerotic subplot."
"A horsey!"
"A human corpse dangling from a meat hook."
"A kid who's never seen a pool, but knows what ""pool"" means anyway."
"A kiss on the lips."
"A legitimate reason to commit suicide."
"A lesbian person."
"A lesbian who doesn’t die."
"A lifespan of three weeks."
"A lifetime of internalized guilt."
"A little girl with a switchblade."
"A long, unforgiving winter."
"A loose end."
"A man so tall and strong, he can wallop anyone."
"A man trying so hard to express an emotion."
"A man who hates fun."
"A man who kills with no qualms."
"A man with a beard who doesn't know shit about cars."
"A mattress full of bed bugs."
"A mean little drawer with nothing inside."
"A meat hook suspension fetish."
"A motherfucking crossbow."
"A motherfucking flamethrower."
"A passionate Latino lover."
"A pattern of defensive wounds."
"A perfectly secluded lake-side cabin where I can tend to my father in peace."
"A person who used to have legs but no longer has legs because I exploded their legs."
"A pile of squirming bodies."
"A pipe bomb."
"A plague unto our people."
"A plastic bag drifting through the wind wanting to start again."
"A plot line that goes nowhere."
"A pound of shrapnel."
"A pregnant forest zebra."
"A protein bar that's full of protein."
"A real fucker."
"A ruptured colon."
"A severe breach of the Hippocratic oath."
"A shallow grave."
"A shark!"
"A shiv straight to the kidneys."
"A shiv."
"A sick lute solo."
"A sledgehammer to the elbow."
"A slow death."
"A slowly expanding puddle of blood."
"A small mound of shoes."
"A solid punch to the spine."
"A splash of hydrochloric acid."
"A squirming ball of mushrooms and severed limbs."
"A stab wound, an explosion, and a fall from a great height."
"A stern, authoritative father."
"A strong horse and enough rations for 30 days."
"A suicide note that nobody cared enough to look for."
"A swivel chair."
"A tall goat called a giraffe."
"A tank. A motherfucking tank. Can you believe that?"
"A tearful confession."
"A teenage girl who won't shut the fuck up about dinosaurs."
"A traumatic childhood experience that forever ruins Halloween."
"A very sharp knife that kills bodies."
"A very tense hoedown."
"A way to explode someone."
"A web of lies."
"A well-placed molotov cocktail."
"A witty remark."
"A woman holding a gun to my head and telling me to relax."
"A woman lead."
"A woman who is both attractive and powerful."
"A woman who is loyal, smart, and funny."
"A zombie with a tragic backstory."
"Abandonment issues."
"Abducting children."
"Abs for days."
"Abs."
"Accidentally executing a hostage."
"Acquiring a gun very easily."
"Actual mutants with medical conditions and no superpowers."
"ADVENTURE!"
"Aimlessly floating downriver."
"Aimlessly swimming hither and thither."
"All manner of horrors."
"All my friends dying."
"All the people I've killed."
"All these body bags filled with the bodies."
"All this sexual tension."
"All-consuming guilt."
"Almost grasping the concept of compassion."
"Amateur lesbian teens."
"America's crumbling infrastructure."
"Amputees."
"An 80% mortality rate."
"An act of terror."
"An emotional gravity that can only be created by a good book or the death of your firstborn."
"An enormous blob of flesh."
"An extremely long elevator ride."
"An old hermit man who is definitely not a pedophile."
"An old, grumpy white guy who is just used to everything."
"An undiscovered body."
"An unfortunate parade of misery."
"An unwanted pregnancy."
"Angst."
"Another unspeakable act of violence."
"Another video game about a bland, frowning white man with stubble."
"Any means necessary."
"Argentinian musician Gustavo Santaolalla."
"Arms like these."
"Asking ""what the fuck?&rdquo;"
"Bangin' it down, raw-dog."
"Barely-concealed hostility."
"Bashing Nora’s head into a fine mist."
"Becoming sad forever."
"Being a burden to others."
"Being a dick to children."
"Being a goddamn badass."
"Being adopted."
"Being all poetic and just losing our minds together."
"Being eaten alive by the physical manifestation of my own poor choices."
"Being in a constant state of anxiety."
"Being knowledgeable in a narrow domain that nobody understands or cares about."
"Being locked in a dog cage for a couple of days."
"Being pummeled with bricks."
"Being so sad all the time."
"Being speared and escaping from death by the sheer power of my own will to live."
"Being too old for this shit."
"Belting out the chorus of a popular song and mumbling through the rest."
"Bigotry."
"Birthdays."
"Biting a woman's ear clean off."
"Bleeding and crying and stuff."
"Bleeding everywhere."
"Blood and guts all over me."
"Bones."
"Botching an execution."
"Boxing up my feelings."
"Bracing for impact."
"Brandishing a gun."
"Broken watches that don’t do the tick-tock."
"Bullets."
"Burning people alive."
"Burying my only daughter."
"Cabinets."
"Carrying a handgun."
"Catching new and mysterious diseases from a South African wheat crop."
"Ceasing to be funny."
"Chaos and bloodshed."
"Childhood friends and the dreams we had."
"Childhood innocence."
"Chokeslamming a child's face into the wall."
"Choking out a 19-year-old."
"Chucking a brick at his face."
"Civilian casualties."
"Coffee."
"Collapsing in grief."
"Coming out."
"Compartment syndrome."
"Complex transgender characters."
"Cordyceps."
"Cowering behind a tree as the hunting dogs close in."
"Cradling my daughter as she bleeds out."
"Crouch-waddling everywhere like I’m doing a poopie."
"Crushing the skulls of enemies underfoot like autumn leaves."
"Cum rag mushrooms."
"Dancing bad."
"Dangling from a noose."
"Death."
"Debilitating childhood trauma."
"Delighting in the pain of others."
"Demanding that everyone lower their weapons right now so we can talk this out."
"Dicking around on the guitar for an hour."
"Dismantling the government."
"Dismemberment."
"Doing some impressive stuff, then going into a deep depression."
"Drifting in and out of consciousness."
"Dry heaving."
"Dubious pseudoscientific nonsense."
"Dumpsters."
"Dying cold, alone, and upside down."
"Eating people."
"Emotional baggage."
"Emotional unavailability."
"Endless stress."
"Enduring."
"Engine trouble."
"Exactly what you deserve."
"Extra ration cards for my little girl."
"Extremely calloused fingers."
"Falling down an elevator shaft."
"Falling in love with poetry."
"Falling into a deathlike slumber for several months."
"Falling six stories onto a stake of rebar."
"False prophets."
"Farm lesbians."
"Feeling lots of feelings."
"Feeling the emotion of anger."
"Feeling what not having hope feels like."
"Feeling your body betraying you every time."
"Ferns."
"Finding out that friendship was the real treasure all along."
"Finding the strength to go on."
"Flopping around for a while before dying."
"Full HD."
"Galloping around the University of Colorado."
"Gangrene, unfortunately."
"Gargling blood as I lie dying on the floor."
"Gayness."
"Gelatinous globules of human flesh."
"Gently smothering a middle-aged man."
"Genuine human connection."
"Getting a girlfriend."
"Getting all the way to Seattle somehow."
"Getting bonked on the head and becoming unconscious."
"Getting called out."
"Getting clubbed."
"Getting everybody killed."
"Getting into a pretty bad car accident."
"Getting off with a warning."
"Getting sniped."
"Getting your arms ripped off."
"Gettin’ ya killed."
"Giving a woman a steak and sending her on her way."
"Giving in to my dark impulses."
"Giving it a good scrub to make sure all the blood is gone."
"Glass shards everywhere."
"Going around punching people."
"Going cannibal."
"Going on an epic adventure and learning a valuable lesson about friendship."
"Going out in a blaze of glory."
"Graphic violence, adult language, and some sexual content."
"Grunting in dismissal."
"Grunting repeatedly, like a man."
"Gun shots to the head."
"Guns."
"Gustavo."
"Guzzling pond water by the bucket."
"Half a puppy."
"Hammering on the door and saying ""open up!&rdquo;"
"Hauling ass."
"Having a full-on mental breakdown at an upscale Wyoming farmhouse."
"Having difficulty coping with the death of a loved one."
"Heartwarming orphans."
"Hiding from border patrol."
"Hiding in the shrubs."
"Holding me tight and telling me everything will be okay."
"Horrible brain injuries."
"How amazing it is to be a mushroom."
"How cool space is."
"How easy it is to climb over a wall with a ladder."
"How easy it is to kill someone."
"How quiet the forest is."
"Huge biceps."
"Hurting those closest to me."
"Improvised explosive devices."
"Incomprehensible cuteness."
"Indescribable loneliness."
"Insatiable bloodlust."
"Ish, the cool man that lives in the sewers."
"Jeffrey Wright roaming the battlefield slaughtering innocent civilians."
"Jiggle physics."
"Jogging from place to place."
"Joining a cult."
"Jumping out at people."
"Kicking a man while he's down."
"Killing anyone who steps foot on my property."
"Killing the sinners."
"Killing time."
"Killing without remorse."
"Knocking out a child with a single punch."
"Latching onto a man's throat and biting out his pulsing jugular."
"Leaping."
"Leaving a trail of grief wherever you go."
"Letting everyone out of jail."
"Lighting stuff on fire."
"Lining people up against a wall and shooting them."
"Live disembowelment."
"Long, solemn silences."
"Losing my daughter at 28."
"Losing my favorite arm."
"Losing my left arm in combat."
"Losing my leg to a roadside bomb."
"Making a pouty face."
"Making out and stuff."
"Massive arms."
"Me and the other wolf boys."
"Men discussing their feelings in an emotionally healthy way."
"Moral ambiguity."
"More than one brick."
"Moss."
"Most of a horse."
"Moving to Wyoming."
"Multiple stab wounds."
"Murdering a trespasser."
"Muscular Greta Thunberg."
"My arsenal of maladaptive coping mechanisms."
"My complicated backstory that you will soon learn about."
"My dead baby daddy."
"My diamond-hard revenge boner."
"My finely curated collection of pornography."
"My first kill."
"My long, long neck."
"My worst fear: ending up alone."
"Nasty crawly things."
"Needless cruelty."
"Never showering."
"Nine seconds of sexual tension, then some kissing."
"Not knowing what an aquarium is."
"Not my real dad!"
"Not only having dry heaves but also wet ones."
"Ominous background music."
"One cool ass kid."
"One titty hanging out."
"Only a very small number of survivors."
"Open and honest communication."
"Our most basic primal instincts."
"Owing a lot of firearms to some very bad people."
"Pallets."
"Panic in the streets."
"Pedophiles."
"Perhaps the end of the human race."
"Piles of baby shoes."
"Pill-popping."
"Pills."
"Planning my child's funeral."
"Plopping down in the corner and letting the fungus claim me."
"Potato. Potato. My little buddy Potato. What a big boy."
"Presenting your documents at the checkpoint."
"Probably just the wind."
"Proving that girls are people too."
"PTSD."
"Punching everyone."
"Punching this wall till it caves."
"Puns."
"Pure muscle."
"Pustules."
"Putting dirty dishes in the sink and hoping someone else deals with them."
"Rage."
"Rapidly-deteriorating peace talks."
"RAWR. Werewolf."
"Realizing that I'm the asshole."
"Releasing a guttural shriek from my vocal sac."
"Repopulating the earth."
"Resorting to cannibalism."
"Revenge."
"Rinsing off all the blood."
"Roach-infested mattresses."
"Rope skills."
"Running out of fuel."
"Safety in numbers and all that."
"Sailing to the rescue."
"Saying a bad word."
"Scooting to the left a little."
"Screaming the F-word."
"Screaming... and then silence."
"Scrotum wound fungus."
"Scuttling across the floor."
"Sea lion polkadots."
"Secreting a cloud of acidic spores from my pustules."
"Seeing my village burned and my family slaughtered before my eyes."
"Self-defense."
"Shaved white heads."
"Sheer force."
"Shitting your pants like a little bitch."
"Shooting first and asking questions later."
"Shooting on sight."
"Shooting people with guns like a big boy."
"Shooting the hell out of a guy."
"Singing sad, soulful songs about my dead father figure."
"Six wretched months in the orphanage."
"Slamming into a table and perishing."
"Slamming through six inches of reinforced concrete."
"Sniffing my crush."
"Sniper! Get down!"
"Sobbing uncontrollably."
"Solving problems with violence."
"Some douche with an acoustic guitar."
"Some really cool dinosaurs."
"Something really funny but I can't remember."
"Soul-crushing silence."
"Spluttering and convulsing."
"Spooky scary skeletons."
"Sprinting for my life."
"Stalkers."
"Strong female characters."
"Stumbling around in the dark."
"Sudden bursts of rage."
"Suddenly being super supportive of gay people."
"Suddenly-intensifying charango music."
"Survival of the fittest."
"Surviving."
"Survivor's guilt."
"Sweating and grunting."
"Sweet, sweet vengeance."
"Taking off each other's clothes enthusiastically."
"Teenage pregnancy."
"Telling you my story, and then trying to kill you with a machete."
"Texas."
"That little voice in the back of your head that tells you to jump when you stand by a cliff."
"That smart son of a bitch, Robert."
"That time my mom died and I was adopted by the homeless guy."
"The 14+ swings it takes to kill a grown man with a golf club."
"The all-knowing sky whale."
"The amount of human suffering I've caused."
"The amount of money I've made selling hardcore drugs."
"The amount of pent-up hate and vitriol I can summon up at any given moment."
"The amount of people my slutty roommate can fuck."
"The artful blood splatter of a perfectly-formed brick colliding with the lower jaw."
"The baby inside me."
"The big ol' horses that do the clip clop."
"The bond between a woman and her horse."
"The charred hole where my face used to be."
"The chick at the party playing &ldquo;Take on Me"" on an acoustic guitar."
"The choke hold."
"The cold hard truth that Daddy never loved you."
"The Cordyceps growing out of my forehead."
"The cycle of violence."
"The damage a powder keg can do to the human groin."
"The dark, sunken eyes of a Gamestop cashier."
"The dull thud of a fallen child."
"The eerie squelch that emanates from a grown man's head when you crush his temple with a golf club."
"The end of the fucking world."
"The euphoric rush of strangling a drifter."
"The ever-present fear of death."
"The fear and hatred in men's hearts."
"The feds that are on their way right now."
"The guilt that pervades my very being."
"The gun I keep on my person at all times."
"The hand that's crushing my windpipe."
"The kind of mustache that makes a parent double check where their child is."
"The majesty of the brontosaurus."
"The manliest masculine man ever to man masculinely."
"The meaninglessness of life."
"The moral ambiguity of my violent actions."
"The morose marathon that is life."
"The most fucked up thing you can imagine."
"The most powerful thing of all: friendship."
"The muffled cries of the hostage."
"The muffled screams coming from the basement."
"The nail bombs that I hid all over town."
"The physical imperfection of an old man."
"The quiet majesty of the giraffe."
"The rash and emotionally driven impulses of a 14-year-old girl."
"The raw anger of Joel."
"The rich history of the Jewish people."
"The sadness that I feel."
"The screams of a person on fire."
"The screams&hellip; the terrible screams."
"The sound of breaking bones."
"The spore cloud that's headed right for us."
"The unbelievable world of mushrooms."
"The urge to kill."
"The very real truth that kids can die."
"The visceral pleasure of revenge."
"The way a sick man’s head just pops when you stomp on it."
"Thinking about all the horrible things that have happened to people."
"Thinking of you as family."
"This dead body I found."
"This fucking weather."
"This here hunt'n rifle."
"Throwing a tantrum and telling everyone not to touch you anymore."
"Treating her like a princess by selling her off to forge an alliance."
"Triceps for days."
"Trying to pass the time by painting a picture."
"Turning into a 14-year-old girl."
"Two arms, one of them gangrenous."
"Two pounds of mix-n'-match nails and screws."
"Two young lovers with nothing better to do."
"Unattended children."
"Unnecessary profanity."
"Unspeakable acts of cruelty."
"Using anger to achieve your goals."
"Vengeance for my father."
"Waiting for the perfect time to strike."
"Watching the life drain from the eyes of father’s killer."
"When the big knife does the stabby stabby."
"When the flashlight isn’t working so you wiggle it and it works just fine."
"Wishing that dogs did not exist anymore so that I wouldn’t have to murder them."
"Wishing we could all just get along."
"Withholding affection."
"Wondering what that sound was."
"Working so hard to have muscles and then having them."
"Young love."
"Zoo animals."
"(This card is not a penis)."
"73647."
"A One-Way Ticket to Penis"
"A Pussy So Tight No Dick Penetrates"
"Alan Wake's American Penis."
"All these cards share a theme. (It's penises)."
"All your penis are belong to us."
"Asian penises."
"Assassin penis."
"Attack of the Penis."
"Back to the Penis."
"Bad Dragon."
"Barfing penis."
"Bastard penis."
"Becca's penis."
"Bet you thought this card wasn't about penises."
"Big Dong."
"Big Mac Penis."
"Bigger blacker penises."
"Biopenis."
"Blue penis."
"BPenis."
"Bronies: The Unexplained Penis."
"BrotherPunk loves penis."
"Bum penis."
"Bunny penis."
"Cadence: Princess of Penis."
"Call of Penis."
"Call of Penis: Penis Ops 2."
"Captain Penis."
"Cards Against Penis."
"Charles <b>Dick</b>ens."
"Charlie Chaplin's penis."
"Clean penis."
"Cloudy With a Chance of Penis."
"CockBox 360."
"CockTube."
"Cocoa penis."
"Crash Bandicock."
"Crotchboob penis."
"Crying penis."
"Cum."
"Currently in use penis."
"Dancing penis."
"Daring Penis."
"DarkPenis."
"Dawn of the Walking Penis."
"Dead Penis."
"Devil May Penis."
"Digipenis."
"Dirty penis."
"Doctor Penis."
"Double Penis All Across The Sky."
"Dragon Penis Z."
"Drinking penis."
"Drunk penis."
"Duck Penis."
"Dungeon and Penises."
"Endless penis."
"Enlarged penis."
"Enter the penis."
"Exploding penis."
"Fallout Penis."
"Family Penis."
"Final Penis."
"Flash: The Quickest Penis."
"Flavored penis."
"FlutterPenis"
"Forehead penis."
"Futapenis."
"Gears Of Penis."
"Gently stroking the penis."
"GERMAN PENIS."
"God of Penis."
"God penis."
"Golden Penis."
"Grand Theft Penis."
"Guess what! Yep, penis."
"Hairy penis."
"Half-Penis 3."
"Happy penis."
"Harry Potter and the Chamber of Penises."
"Harry Potter and the Deadly Penisesfire."
"Harry Potter and the Half-lord of Penis."
"Harry Potter and the Penis of Fire."
"Hat and cane penis."
"Hello Penis."
"Herm penis."
"Heroes of Penis."
"Horse cock."
"Horse penis."
"Horton Hears a Penis."
"How To Train Your Penis."
"Hurricane penis"
"I Am Penis."
"I don't even penis."
"Incredible penis."
"Inflatable penis."
"Iron Penis."
"IT penis."
"It's all about the size."
"James Cock."
"Jurassic Penis."
"Kung Fu Penis."
"Large penis."
"Legend of Penis."
"Lonely penis."
"Lord Of Penises."
"Lord of the Penis: The Two Vaginas."
"Macropenis."
"Mass Penis."
"Medal Of Penis."
"Medieval Penis."
"Metro Penis."
"Micropenis."
"Microsoft Penis."
"Morning wood."
"Mortal Penis."
"Mr Bean's penis."
"Multicolored penis."
"Multiple penis stabs."
"My brother's penis."
"My Little Penis: Friendship is Vagina."
"My Little Pony: Penis is Magic."
"My penis."
"Need For Penis."
"Neutral penis."
"Nightmare Penis."
"No penis."
"Orange penis."
"P2P - Penis2Penis."
"P3n15."
"Peach penis."
"Penis 64."
"Penis Against Humanity."
"Penis Age 2."
"Penis Alone."
"Penis boy."
"Penis claws."
"Penis Crashers."
"Penis Daily."
"Penis Dew."
"Penis Empire."
"Penis Fantasy."
"Penis FIFA World Cup."
"Penis in a box."
"Penis in the night."
"Penis Master."
"Penis May Cry."
"Penis Must Die."
"Penis nostalgia."
"Penis Of Honor."
"Penis of the Year."
"Penis or no penis."
"Penis Paradise."
"Penis Park."
"Penis Penis Revolution."
"Penis penis."
"Penis princess."
"Penis Row 4."
"Penis Scrolls."
"Penis Shippuuden."
"Penis Simulator 2013."
"Penis stimulator."
"Penis with a hat."
"Penis wood."
"Penis: The Final Frontier."
"Penis: This is your life."
"PenisAura."
"Penisbound."
"Peniscraft."
"PenisCube."
"Penises From Iwo Jima."
"Penises From Outer Space."
"Penises in bags."
"PenisPunk."
"PenisSide 2."
"PenisStation 3."
"Penistia."
"Pink Fluffy Penises Dancing In Vaginas."
"Pirates of the Penis."
"PocketPenis."
"Poke penis."
"Polish penis."
"Pony penis."
"PowerPuff Penis."
"Princess Penis."
"Rarity."
"Rebecca Cock."
"Red Penis Redemption."
"Refresh page penis."
"Return of the Penis."
"Revenge of the Penis."
"Rise of the Penis."
"Robin: No penis."
"Robopenis!
"Robopenis!
"Roller Penis Tycoon."
"Romantic penis."
"Sad penis."
"Saving Private Penis."
"Saving Ryan's Privates."
"Shredded penis."
"Silent Penis."
"Sketchy Penis."
"Small penis."
"Space penis."
"Spyro: Dawn of the Penis."
"Stabbing yourself with a penis."
"Star Penis: The Virgin Wars."
"Star Wars: The Penis Wars."
"Suck my penis!"
"Super Penis."
"Surgeon Simulator 2013 with a dick replacement mod."
"Swedish Penis."
"Team Penis 2."
"Teenage Mutant Ninja Penis"
"The Anal, The Vagina And The Penis."
"The Binding of Penis."
"The Chosen Penis."
"The Chronicles of Penis."
"The Elder Penises."
"The Elements of Penis."
"The Fantastic Bean."
"The Great British Penis."
"The Holy Penis."
"The Life and Times of Penis."
"The Life of Penis."
"The Magic Penis."
"The Mane Penis."
"The Manliest Penis."
"The One Penis to rule them all."
"The Penis Express."
"The Penis Massacre."
"The penis must flow."
"The Penis Network."
"The Penis of Resistance."
"The Penis Page."
"The Penis Strikes Back."
"The penis that wasn't a penis."
"The Queen's penis."
"The Rednose Penis."
"The smallest whitest penis."
"The weakest penis."
"The wrong penis."
"Titanic: The Story of a Penis."
"Tom and Penis."
"Tom Clancy's Penis."
"Tons of penises."
"Tony Hawk's Penis."
"Tree fiddy penis."
"Trout penis."
"Twat penis."
"Ultimate Penis."
"United Penises."
"Unreal Penis."
"Use the Penis."
"Used penis."
"Robopenis!"
"Vagina."
"Viking penis."
"Virgin penis."
"Virtual penis."
"Wang Commander."
"Wanker penis."
"Wonder Penis."
"World War Penis."
]
